version: '3'
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: quarkusdb
  application:
    build: 
      context: .
      dockerfile: src/main/docker/Dockerfile
    ports:
    - 8080:8080
    environment:
      POSTGRES_HOST: postgres
    depends_on:
    - postgres
  prometheus:
    build: prometheus
    ports:
    - 9090:9090
    depends_on:
    - application    
  grafana:
    build: grafana
    ports:
    - 3000:3000
    depends_on:
    - prometheus

